spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver

blogConfig:
  salt: hello,blog_3c209f2f54da8fffe25b37388e2
  username: root
  password: initroot

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com:
      yzmoe:
        warn

server:
  port: 8000
  tomcat:
    max-connections: 100
    max-threads: 50
