server:
  port: 80
#  http2:
#    enabled: true
#  compression:
#    enabled: true
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12 # 启用http2
#    key-store-password: 12345678 # 证书密码
#    key-store-type: PKCS12 # 证书类型
#    protocol: TLSv1.2 # 协议类型
#    key-alias: undertow
# pictures upload size limit
#spring:
#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 20MB
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 12345678
#    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai

# set datasource
spring:
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver



blogConfig:
  salt: hello,blog_3c209f2f54da8fffe25b37388e2
  username: root
  password: initroot
logging:
  level:
    com:
      yzmoe:
        personalblog:
          trace
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


